# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb48cd82d546418d95553321ae63662ce253391087d7775c2b5fdc205e75b6f119276836579f9c1ff1ddcfa01fb6818c5f9b6cb8f7f8c8b5ff5b54522a282ddd

test:
  secret_key_base: 38acd173981e8752b1b5039b4b7867342596580fa0a0962f7de84d181d42bb840c3faac493475e68b948dec8fdc02cc7dcde7ac8490ad9f162507edbadf36e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
